// <auto-generated />
using System;
using FlightScheduleRepository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightScheduleRepository.Migrations
{
    [DbContext(typeof(WellsFargoFlightScheduleDBContext))]
    [Migration("20231201071511_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightScheduleRepository.Models.Flight", b =>
                {
                    b.Property<string>("FlightNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("FlightNo");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("FlightScheduleRepository.Models.FlightSchedule", b =>
                {
                    b.Property<string>("FlightNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArriveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FlightNo", "TravelDate");

                    b.ToTable("FlightSchedule");
                });

            modelBuilder.Entity("FlightScheduleRepository.Models.FlightSchedule", b =>
                {
                    b.HasOne("FlightScheduleRepository.Models.Flight", "Flight")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("FlightNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightScheduleRepository.Models.Flight", b =>
                {
                    b.Navigation("FlightSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
