// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationRepository.Models;

#nullable disable

namespace ReservationRepository.Migrations
{
    [DbContext(typeof(WellsFargoReservationDBContext))]
    partial class WellsFargoReservationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationRepository.Models.FlightSchedule", b =>
                {
                    b.Property<string>("FlightNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FlightNo", "TravelDate");

                    b.ToTable("FlightSchedule");
                });

            modelBuilder.Entity("ReservationRepository.Models.ReservationDetail", b =>
                {
                    b.Property<string>("PNRNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("PassengerNo")
                        .HasColumnType("int");

                    b.Property<short?>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PNRNo", "PassengerNo");

                    b.ToTable("ReservationDetail");
                });

            modelBuilder.Entity("ReservationRepository.Models.ReservationMaster", b =>
                {
                    b.Property<string>("PNRNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("FlightNo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("NoOfPassengers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PNRNo");

                    b.HasIndex("FlightNo", "TravelDate");

                    b.ToTable("ReservationMaster");
                });

            modelBuilder.Entity("ReservationRepository.Models.ReservationDetail", b =>
                {
                    b.HasOne("ReservationRepository.Models.ReservationMaster", "ReservationMaster")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("PNRNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationMaster");
                });

            modelBuilder.Entity("ReservationRepository.Models.ReservationMaster", b =>
                {
                    b.HasOne("ReservationRepository.Models.FlightSchedule", "FlightSchedule")
                        .WithMany("ReservationMasters")
                        .HasForeignKey("FlightNo", "TravelDate");

                    b.Navigation("FlightSchedule");
                });

            modelBuilder.Entity("ReservationRepository.Models.FlightSchedule", b =>
                {
                    b.Navigation("ReservationMasters");
                });

            modelBuilder.Entity("ReservationRepository.Models.ReservationMaster", b =>
                {
                    b.Navigation("ReservationDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
